name: expensepredict
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0 # Untuk manajemen font
  fl_chart: ^0.66.0 # Untuk visualisasi grafik
  provider: ^6.1.1 # State management
  shared_preferences: ^2.2.2 # Penyimpanan lokal
  intl: 0.19.0 # Format tanggal dan angka
  animations: ^2.0.11 # Animasi custom
  lottie: ^3.0.0 # Animasi JSON
  shimmer: ^3.0.0 # Loading effect
  curved_navigation_bar: ^1.0.3 # Navbar custom
  http: ^1.1.0 # HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nickelodeon
      fonts:
        - asset: assets/fonts/Nickelodeon.ttf
